#!/bin/bash

service npcd start
service rrdcached start

# Allow any signal which would kill a process to stop server
trap "service npcd stop" HUP INT QUIT ABRT ALRM TERM TSTP

while pgrep -u icinga2 npcd > /dev/null; do sleep 5; done
