#!/bin/bash
#Original file from jjethwa/icinga2

# enable necessary features
icinga2 feature enable ido-mysql livestatus compatlog perfdata notification command

#icinga2 API cert - regenerate new private key and certificate when running in a new container
	#Make sure the directories exist
	mkdir -p /var/lib/icinga2/certs
	chown -R nagios:nagios /var/lib/icinga2/certs
	#Create and self-sign a master certificate
	icinga2 node setup --master --cn $(hostname)	
	#Write zone file
	cat <<EOF >/etc/icinga2/zones.conf
	#Generated (with variables!) by docker
	
	#Ourselves (the master):
	object Endpoint "$(hostname)" {
	host = "$(hostname)"
	}
	
	#Ourselves and our zone (master zone):
	object Zone "${ICINGA2_ZONE}" {
	endpoints = [ "$(hostname)" ]
	}
		
	#Global commands (on master)
	object Zone "global-templates" {
  	global = true
	}
	
EOF


