#!/bin/bash

# Set localtime
unlink /etc/localtime
ln -s /usr/share/zoneinfo/${LOCALTIME} /etc/localtime
echo "Time set to ${LOCALTIME}"

# Config: we separate db config from file config

# File config
# If we cannot find magic file, create the configuration
if [ ! -f "/etc/icingaweb2/CONFIGURED" ]; then
  /opt/setup/icingaweb2
fi

# DB config
mysql="mysql --connect-timeout=10 -h sql -u root -p${MYSQL_ROOT_PASSWORD}"

# Wait until MariaDB container is ready
echo "Starting DB configuration... waiting for DB container"
while ! $mysql -e status &> /dev/null; do
  sleep 1s
  echo -n "."
done

# If we cannot find our directory in mysql, connect to the DB
if [ ! -d "/var/lib/mysql/icingaweb2" ]; then
  # Hash the icingaweb2 admin pass
  export ICINGAWEB2_ADMIN_PASS_HASH=$(openssl passwd -1 "${ICINGAWEB2_ADMIN_PASS}")
  # set $mysql alias
  
  # create and grant access to DB
  $mysql <<-END
    CREATE DATABASE IF NOT EXISTS icingaweb2;
    GRANT SELECT, INSERT, UPDATE, DELETE, DROP, CREATE VIEW, INDEX, EXECUTE ON icingaweb2.* TO 'icingaweb2'@'%' IDENTIFIED BY '${ICINGAWEB2_PASSWORD}';
END
  
  $mysql icingaweb2 < /usr/share/icingaweb2/etc/schema/mysql.schema.sql
  
  $mysql <<-END
    USE icingaweb2;
    INSERT IGNORE INTO icingaweb_user (name, active, password_hash) VALUES ('${ICINGAWEB2_ADMIN_USER}', 1, '${ICINGAWEB2_ADMIN_PASS_HASH}');
END
fi

# Director conf
# This should ideally go into "core", but then it requires the configfiles in /etc/icinga2
# as well as DB configuration, hence I put it here, to keep it kinda together.
echo "Creating DB director..."
if [ ! -d "/var/lib/mysql/director" ]; then
  $mysql <<-END
    CREATE DATABASE IF NOT EXISTS director;
    GRANT ALL ON director.* TO 'director'@'%' IDENTIFIED BY '${DIRECTOR_USER_PASSWORD}';
END
fi

if ! id "icingadirector" &>/dev/null; then
  /opt/setup/director
fi

# If we cannot find nagvis conf, run conf script
if [ ! -f "/usr/local/nagvis/etc/nagvis.ini.php" ]; then
  /opt/setup/nagvis
fi

# Ensure that nagvis site is enabled
if [ ! -f "/etc/apache2/sites-enabled/nagvis.conf" ]; then
  a2ensite nagvis
  service apache2 reload
fi

# Ensures that icingaweb2 have www-data: privileges
chown -R www-data: /etc/icingaweb2

# Check for an available internet connection
if ping -q -c 1 -W 1 8.8.8.8 >/dev/null; then
  ntpd -gq
  service ntp start
fi

/usr/bin/supervisord -c /etc/supervisor/supervisord.conf -n &
trap "supervisorctl shutdown && wait" SIGTERM
wait
