#!/bin/bash

# Add the user to run its daemon
if ! id "icingadirector" &>/dev/null; then
  useradd -r -g icingaweb2 -G www-data -d /var/lib/icingadirector -s /bin/false icingadirector
fi
if [ ! -e /var/lib/icingadirector ] ; then
  install -d -o icingadirector -g icingaweb2 -m 0750 /var/lib/icingadirector
fi
su - icingadirector -s /bin/bash -c "/usr/bin/icingacli director daemon run" &

# Run the DB migration
icingacli director migration run --verbose

