#!/bin/bash

export DEBIAN_SYS_MAINT_PASSWORD=${DEBIAN_SYS_MAINT_PASSWORD:-$(pwgen -s 15 1)}
export ICINGA_PASSWORD=${ICINGA_PASSWORD:-$(pwgen -s 15 1)}
export IDO_PASSWORD=${IDO_PASSWORD:-$(pwgen -s 15 1)}

/opt/setup/icinga2

cat <<-END
===================================================================
MySQL user 'root' was set by the MariaDB container to ${MYSQL_ROOT_PASSWORD}
MySQL user 'debian-sys-maint' password set to ${DEBIAN_SYS_MAINT_PASSWORD}
MySQL user 'icinga' password set to ${ICINGA_PASSWORD}
MySQL user 'icinga2-ido-mysq' password set to ${IDO_PASSWORD}
===================================================================


Starting Supervisor.
END

icinga2 daemon --validate

ntpd -gq
service ntp start

/usr/bin/supervisord -c /etc/supervisor/supervisord.conf -n &
trap "supervisorctl shutdown && wait" SIGTERM
wait
