#!/bin/bash

if [ ! "$(ls -A /etc/icinga2/conf.d)" ]; then
 
/opt/setup/icinga2

cat <<-END
===================================================================
MariaDB user 'root' was set in the secret file to ${MYSQL_ROOT_PASSWORD}
Icinga2idomysql password was set in the secret file to ${ICINGA_PASSWORD}
===================================================================

END
fi

#START ICINGA2
echo "=> Starting Icinga2"

icinga2 daemon --validate

ntpd -gq
service ntp start

/usr/bin/supervisord -c /etc/supervisor/supervisord.conf -n &
trap "supervisorctl shutdown && wait" SIGTERM
wait
